version: '3.4'

services:
  openwebui:
    image: openwebui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - GPU=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  open-webui_default:
    external: true
